name: CMake for multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Install external dependencies
      run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

    - name: Configure CMake
      run: bash ${{github.workspace}}/gh/init_cmake.sh ${{github.workspace}} ${{github.workspace}}/build

    - name: Build for Ubuntu Linux
      run: cmake --build ${{github.workspace}}/build
  android:
    runs-on: ubuntu-latest
    strategy:
        matrix:
           arch: ['arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64']

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Install external dependencies
      run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

    - name: Build for Android
      run: bash ${{github.workspace}}/gh/android.sh ${{github.workspace}} ${{matrix.arch}}

    - uses: actions/upload-artifact@v4
      with:
          name: android-artifact-${{matrix.arch}}
          path: ${{github.workspace}}/lib
          if-no-files-found: error
  apk:
    runs-on: ubuntu-latest
    needs: android

    steps:
    - uses: actions/checkout@v4

    - name: Download compiled libraries
      uses: actions/download-artifact@v4
      with:
        path: lib

    - name: Install external dependencies
      run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

    - name: Generate an APK file
      run: bash ${{github.workspace}}/gh/apk.sh ${{github.workspace}}
