name: CMake for multiple platforms

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install external dependencies
        run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

      - name: Configure CMake
        run: bash ${{github.workspace}}/gh/init_cmake.sh ${{github.workspace}} ${{github.workspace}}/build

      - name: Build for Ubuntu Linux
        run: cmake --build ${{github.workspace}}/build
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64-v8a", "armeabi-v7a", "x86_64"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install external dependencies
        run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

      - name: Build for Android
        run: bash ${{github.workspace}}/gh/android.sh ${{github.workspace}} ${{matrix.arch}}

      - uses: actions/upload-artifact@v4
        with:
          name: android-artifact-${{matrix.arch}}
          path: |
            ${{github.workspace}}/lib
            ${{github.workspace}}/logs
          if-no-files-found: error
  apk:
    runs-on: ubuntu-latest
    needs: android

    steps:
      - uses: actions/checkout@v4

      - name: Download compiled libraries
        uses: actions/download-artifact@v4
        with:
          path: lib

      - name: Install external dependencies
        run: bash ${{github.workspace}}/gh/ubuntu_deps_x86_64.sh

      - name: Generate the APK file
        run: bash ${{github.workspace}}/gh/apk.sh ${{github.workspace}}

      - name: Load keystore
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: echo "$SIGNING_KEY" | base64 --decode > bin/.keystore

      - name: Sign the APK
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ANDROID_API: ${{ secrets.ANDROID_API }}
        run: |
          # Find the highest version of build-tools
          BUILD_TOOLS_DIR=$(ls -1 $ANDROID_HOME/build-tools/*/ | sort -V | head -n 1)
          echo "build tools dir: $BUILD_TOOLS_DIR"

          # Sign the APK
          ${BUILD_TOOLS_DIR}apksigner sign \
            --ks bin/.keystore \
            --ks-pass pass:$KEY_STORE_PASSWORD \
            --key-pass pass:$KEY_PASSWORD \
            --min-sdk-version $ANDROID_API \
            bin/app.apk

      - uses: actions/upload-artifact@v4
        with:
          name: fightable-android-universal
          path: bin/app.apk
          if-no-files-found: error
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: Set up Clang
      #   uses: egor-tensin/setup-clang@v2
      #   with:
      #     version: latest
      #     platform: x64

      - name: Download dependencies
        run: gh/win_deps.ps1

      - name: Download Ninja
        run: choco install ninja

      - name: Update vcpkg.json
        run: gh/win_vcpkg_baseline.ps1

      # - name: Setup vcpkg
      #   uses: lukka/run-vcpkg@v11
      #   with:
      #     vcpkgJsonGlob: "**/vcpkg.json"

      - name: Build project
        run: gh/win_build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: fightable-windows-x86_64
          path: ${{github.workspace}}/winout
          if-no-files-found: error
